### ISSUE TITLE
CV look at 100% zoom chrome linux

### ISSUE THREAD

**Issue by RamiDaoud1979-zz** [RamiMhanna/powercoders#1]
Good morning Rami,

I noticed an overlap between elements when rendering on the setting per subject. Can you try rendering your cv on same settings but please push ctrl + 0 to reset your browser in developer mode.
![mhanna at 100] 
https://user-images.githubusercontent.com/22483897/50051507-dd47fe00-0113-11e9-8ec3-a174056959fb.png

**Comment by RamiMhanna** [comment]
Thank you very much, Rami Daoud, the bug is fixed.
